### ISSUE TITLE
[Feature Request] Add link to flathub on README

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [emericg/toolBLEx#16]
**Is your feature request related to a problem? Please describe.**
I want to install this app

**Describe the solution you'd like**
This badge
<a href='https://flathub.org/apps/io.emeric.toolblex'>
  <img width='240' alt='Download on Flathub' src='https://dl.flathub.org/assets/badges/flathub-badge-en.png'/>
</a>

**Describe alternatives you've considered**
Set the repo's homepage to the flathub link

**Comment by emericg** [comment]
Alright here you go ^^
