### ISSUE TITLE
0.12 not running after first launch when using Qt6 8.0

### ISSUE THREAD

**Issue by parkerlreed** [emericg/toolBLEx#19]
**Describe the bug**

After running and closing 0.12, subsequent launches fail without any messaging. Clearing data file for toolBLEx has no effect.

Possibly related to testing Qt6 8.0

Strace log 
[strace.txt](https://github.com/user-attachments/files/15905794/strace.txt)

**Expected behavior**

Program to relaunch

**To Reproduce**
1. Run 0.12 (Compiled with Qt6)
2. Close the program
3. Attempt to relaunch

**Your environment**
Please describe the environment you are using:
1. Arch Linux
2. Compiled fro source
3. cd2976c877b308886db4d31b282f7d16ef38b308

**Additional context**

```
qt6-base 6.8.0beta1-2
```

```
[parker@rogally bin]$ rm -rf ~/.cache/toolBLEx/
[parker@rogally bin]$ rm -rf ~/.config/toolBLEx/
[parker@rogally bin]$ rm -rf ~/.local/share/toolBLEx/
[parker@rogally bin]$ ./toolblex 
[parker@rogally bin]$
```

**Comment by parkerlreed** [comment]
Ok I rebooted the system and it seems to be fine now... Subsequent launches are acting as expected. Not sure what was going on there.

**Comment by emericg** [comment]
Hi,
It may be because of Qt 6.8 (or because you just switched, and cleaning the build is sometimes necessary), but given the symptom (it doesn't even start right?) it may be because of the code that prevent multiple instances running in parallel.

If it happens again, you can try editing this line in the main.cpp (set the third parameter to true instead of false)

> SingleApplication app(argc, argv, false);

That code has been mostly broken since Qt 6.6, and I'm contemplating disabling it until it's rewritten upstream, because it's not technically required for toolBLEx and it can cause some real problems.

**Comment by parkerlreed** [comment]
Figured out what triggers it for me. Ctrl C'ing the application from terminal causes it not to relaunch at all.

Making the change to SingleApplication to set it to true does fix the issue.

```
[parker@rogally bin]$ ./toolblex 
qt.bluetooth.bluez: Missing CAP_NET_ADMIN permission. Cannot determine whether a found address is of random or public type.
qrc:/qml/PanelDeviceInfos.qml:94:21: QML TextSelectable: Binding loop detected for property "implicitWidth"
qrc:/qml/AdapterWidget.qml:137:13: QML TextSelectable: Binding loop detected for property "implicitWidth"
qrc:/qml/AdapterWidget.qml:83:13: QML TextSelectable: Binding loop detected for property "implicitWidth"
qrc:/qml/PanelDeviceInfos.qml:266: TypeError: Cannot read property 'pairingStatus' of null
qrc:/qml/PanelDeviceInfos.qml:346: TypeError: Cannot read property 'majorClass' of null
qrc:/qml/PanelDeviceInfos.qml:371: TypeError: Cannot read property 'majorClass' of null
qrc:/qml/PanelDeviceInfos.qml:386: TypeError: Cannot read property 'servicesCount' of null
qrc:/qml/PanelDeviceInfos.qml:396: TypeError: Cannot read property 'serviceClass' of null
qrc:/qml/PanelDeviceInfos.qml:629: TypeError: Cannot read property 'mtu' of null
qrc:/qml/PanelDeviceInfos.qml:675: TypeError: Cannot read property 'rssi' of null
qrc:/qml/PanelDeviceInfos.qml:821: TypeError: Cannot read property 'servicesCount' of null
^C
[parker@rogally bin]$ ./toolblex 
[parker@rogally bin]$ ./toolblex 
[parker@rogally bin]$ 
```
