### ISSUE TITLE
[Feature Request] Selectable data export location

### ISSUE THREAD

**Issue by jsmif** [emericg/toolBLEx#4]
**Is your feature request related to a problem? Please describe.**
I can't find where the data is exported to

**Describe the solution you'd like**
I would like to select where it's exported to

**Describe alternatives you've considered**
You could print where the data is exported to

**Comment by emericg** [comment]
> I would like to select where it's exported to

Yes that make sense, I'll try to do that tomorrow.

> I can't find where the data is exported to

The default export path is supposed to be the user's home directory + /toolBLEx/ + name of the sensor (I should probably add the MAC address too).

**Comment by emericg** [comment]
I finally added the file chooser for the data export (and the mac/uuid in the default filename).

You can test the new builds here: https://github.com/emericg/toolBLEx/actions
I still want to improve the way the software connect/scan/disconnect and export data, but after that I'll do a proper release.
