### ISSUE TITLE
Write to characteristic (data) seems to write as string instead

### ISSUE THREAD

**Issue by jjcf89** [emericg/toolBLEx#7]
**Describe the bug**
A Write to characteristic (data) seems to write as string instead

**Expected behavior**

Input a hex string to send to device, window shows hex values I want written.
![image](https://github.com/emericg/toolBLEx/assets/648286/81d23d0d-8fc9-4254-9e36-5c66516e565c)

After hitting "Write value", characteristic shows write as a string.
![image](https://github.com/emericg/toolBLEx/assets/648286/7648b687-6b95-4d0a-ba58-a33e5d839c84)

**Your environment**
Please describe the environment you are using:
1. What is your operating system
Windows 10
3. Where did you download/bought the application
From github
5. The version of the application you are running
Latest release

**Additional context**

**Comment by emericg** [comment]
That's indeed a bug, I'll have a look this week.

**Comment by emericg** [comment]
OK sorry for the long delay on this one, but I just wasn't working on this software...
The writes were quite buggy, now the code has been corrected and simplified, hopefully everything is good now!

You can test the new builds here: https://github.com/emericg/toolBLEx/actions
I still want to improve the way the software connect/scan/disconnect and export data, but after that I'll do a proper release.
